server:
  port: 9090
  error:
    whitelabel:
      enabled: true

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb-dev
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
welcome:
  message: Welocme to java springboot world !!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  profiles: qa
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb-qa
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
welcome:
  message: Welocme to java springboot world !!!

---

spring:
  profiles: prod
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb-prod
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
welcome:
  message: Welocme to java springboot world !!!